siteMain/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using siteMain.Areas.Admin.Model;
using siteMain.Domain;

namespace siteMain.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly DataManager _dataManager;

        public HomeController(DataManager dataManager)
        {
            _dataManager = dataManager;
        }
        
        public IActionResult Index()
        {
            return View("Index", new FilmsAndActorsAdmin()
            {
                Films = _dataManager.Films.GetFilms(),
                Actors = _dataManager.Actors.GetActors()
            });
        }
    }
}

siteMain/Areas/Admin/Controllers/TextFieldsController.cs
using Microsoft.AspNetCore.Mvc;
using siteMain.Domain;
using siteMain.Domain.Entities;
using siteMain.Service;

namespace siteMain.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class TextFieldsController : Controller
    {
        private readonly DataManager _dataManager;
        public TextFieldsController(DataManager dataManager)
        {
            _dataManager = dataManager;
        }

        public IActionResult Edit(string codeWord)
        {
            var textFieldsByCodeWord = _dataManager.TextFields.GetTextFieldsByCodeWord(codeWord);
            return View(textFieldsByCodeWord);
        }

        [HttpPost]
        public IActionResult Edit(TextFields model)
        {
            if (ModelState.IsValid)
            {
                _dataManager.TextFields.SaveTextFields(model);
                return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
            }
            return View(model);
        }
    }
}

siteMain/Controllers/ActorsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using Microsoft.AspNetCore.Identity;
using siteMain.Domain;
using siteMain.Domain.Entities;
using siteMain.Models;
using siteMain.Service;

namespace siteMain.Controllers
{
    public class ActorsController : Controller
    {
        private readonly DataManager _dataManager;
        readonly UserManager<IdentityUser> _manager;

        public ActorsController(DataManager dataManager, UserManager<IdentityUser> manager)
        {
            _dataManager = dataManager;
            _manager = manager;
        }

        public IActionResult Index(Guid id, string sortOrder)
        {
            if (id != default)
            {
                var actor = _dataManager.Actors.GetActorsById(id);
                
                return View("ShowActor", new ActorsEdit
                {
                    Id = actor.Id,
                    Title = actor.Title,
                    AvgRateActor = actor.AvgRateActor,
                    TitleImagePath = actor.TitleImagePath,
                    Text = actor.Text,
                    UsersId = _manager.GetUserId(User),
                    GetUserById = _dataManager.UserRateActors.GetUserByIdFilm(actor.Id.ToString(), _manager.GetUserId(User)).Count() == 1,
                    UsersMark = _dataManager.UserRateActors.GetUserMark(actor.Id.ToString(), _manager.GetUserId(User)),
                    FilmsAndActors = actor.FilmsAndActors.Select(x => new FilmsAndActorsModel
                    {
                        Title = _dataManager.Films.GetFilmsById(x.IdFilm).Title,
                        Id = _dataManager.Films.GetFilmsById(x.IdFilm).Id
                    }).ToList()
                });
            }

            ViewBag.TextField = _dataManager.TextFields.GetTextFieldsByCodeWord("PageServices");
            ViewBag.DateSortParm = sortOrder == "Avg" ? "Avg": "avg_desc";
            var sort = _dataManager.Actors.GetActors();
            
            switch (sortOrder)
            {
                case "avg_desc":
                    sort = sort.OrderByDescending(s => s.AvgRateActor);
                    break;
                case "Avg":
                    sort = sort.OrderBy(s => s.AvgRateActor);
                    break;
            }
            return View(sort);
        }
        [HttpPost]
        public IActionResult Mark(Mark mark, UserRatesActors model, Guid id)
        {
            var actors = _dataManager.Actors.GetActorsById(id);
            var avg = new AvgRateActor(_dataManager);

            model.UsersId = _manager.GetUserId(User).ToString();
            model.RateActor = mark.MarkValue;
            model.IdActor = actors.Id;
            
            _dataManager.UserRateActors.SaveUserRate(model);
            avg.UpdateAvg(actors.Id);

            return RedirectToAction(nameof(Index), nameof(ActorsController).CutController());
        }
    }
}

siteMain/Controllers/FilmsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using siteMain.Domain;
using siteMain.Domain.Entities;
using siteMain.Models;
using siteMain.Service;

namespace siteMain.Controllers
{
    [Authorize]
    public class FilmsController : Controller
    {
        private readonly DataManager _dataManager;
        readonly UserManager<IdentityUser> _manager;
        
        public FilmsController(DataManager dataManager, UserManager<IdentityUser> manager)
        {
            _dataManager = dataManager;
            _manager = manager;
        }
        
        public IActionResult Index(Guid id, string sortOrder)
        {
            if (id != default)
            {
                var filmsById = _dataManager.Films.GetFilmsById(id);

                return View("Show", new FilmsEdit()
                {
                    Id = filmsById.Id,
                    Title = filmsById.Title,
                    AvgRateFilm = filmsById.AvgRateFilm,
                    TitleImagePath = filmsById.TitleImagePath,
                    Text = filmsById.Text,
                    UsersId = _manager.GetUserId(User),
                    GetUserById = _dataManager.UserRateFilms.GetUserByIdFilm(filmsById.Id.ToString(), _manager.GetUserId(User)).Count() == 1,
                    UsersMark = _dataManager.UserRateFilms.GetUserMark(filmsById.Id.ToString(), _manager.GetUserId(User)),
                    FilmsAndActors = filmsById.FilmsAndActors.Select(x=>new FilmsAndActorsModel()
                    {
                        Title = _dataManager.Actors.GetActorsById(x.IdActor).Title,
                        Id = _dataManager.Actors.GetActorsById(x.IdActor).Id
                    }).ToList()
                });
            }

            ViewBag.DateSortParm = sortOrder == "Avg" ? "Avg" : "avg_desc";
            var sort = _dataManager.Films.GetFilms();

            switch (sortOrder)
            {
                case "avg_desc":
                    sort = sort.OrderByDescending(s => s.AvgRateFilm);
                    break;
                case "Avg":
                    sort = sort.OrderBy(s => s.AvgRateFilm);
                    break;
            }
            return View(sort);
        }
        [HttpPost]
        public IActionResult Mark(Mark mark, UserRatesFilm model, Guid id)
        {
            var filmsById = _dataManager.Films.GetFilmsById(id);
            var avg = new AvgRateFilm(_dataManager);
            
            model.UsersId = _manager.GetUserId(User);
           // model.UserName = _manager.GetUserName(User);
            model.RateFilm = mark.MarkValue;
            model.IdFilm = filmsById.Id;
           // model.Title = filmsById.Title;
            model.RateFilm = mark.MarkValue;
           
            _dataManager.UserRateFilms.SaveUserRate(model);
            avg.UpdateAvg(filmsById.Id);

            return RedirectToAction(nameof(Index), nameof(FilmsController).CutController());
        }
    }
}

siteMain/Areas/Admin/Views/Home/Index.cshtml
@model FilmsAndActorsAdmin
@{
    string strTitle = "Панель администратора";
    ViewBag.Title = strTitle;
}

<div>
    <h3>@strTitle</h3>
    <div>
        <h3>Фильмы</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="Films" asp-action="Edit" asp-route-id="">Добавить фильм</a>
        </div>
        @if (Model.Films.Any())
        {
            <div>
                @foreach (Films entity in Model.Films)
                {
                    <div>
                        <a asp-area="Admin" asp-controller="Films" asp-action="Edit" asp-route-id="@entity.Id">редактировать</a>
                        |
                        <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="Films" asp-action="Delete" method="post">
                            <input type="hidden" name="id" value="@entity.Id">
                            <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">удалить</a>
                        </form>
                        |
                        <a asp-area="" asp-controller="Films" asp-action="Index" asp-route-id="@entity.Id">
                            @($"{entity.Title}")
                        </a>
                    </div>
                }
            </div>
        }
    </div>

    <div>
        <h3>Актеры</h3>
        <div class="div-box">
            <a asp-area="Admin" asp-controller="ActorControllerAdmin" asp-action="EditActor" asp-route-id="">Добавить актера</a>
        </div>
        @if (Model.Actors.Any())
        {
            <div>
                @foreach (Actors entity in Model.Actors)
                {
                    <div>
                        <a asp-area="Admin" asp-controller="ActorControllerAdmin" asp-action="EditActor" asp-route-id="@entity.Id">редактировать</a>
                        |
                        <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="ActorControllerAdmin" asp-action="Delete" method="post">
                            <input type="hidden" name="id" value="@entity.Id">
                            <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">удалить</a>
                        </form>
                        |
                        <a asp-area="" asp-controller="Actors" asp-action="Index" asp-route-id="@entity.Id">
                            @($"{entity.Title}")
                        </a>
                    </div>
                }
            </div>
        }
    </div>

    <div class="div-box">
        <h3>Редактировать страницы сайта</h3>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex">Главная</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageServices">Наши услуги</a>
        <a asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageContacts">Контакты</a>
    </div>
    <div class="div-box">
        <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
            <input type="submit" value="Выйти" />
        </form>
    </div>
</div>